//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS17.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Interview
    {
        [Display(Name = "Interview ID")]
        public int InterviewId { get; set; }
        [Display(Name = "M#")]
        public string MNumber { get; set; }
        [Display(Name = "Interview Company")]
        public string InterviewCompany { get; set; }
        [Display(Name = "Interview Date")]
        public System.DateTime InterviewDate { get; set; }
        public Nullable<bool> Offer { get; set; }
    
        public virtual StudentAlum StudentAlum { get; set; }
    }
}
